version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=llama3-8b-8192
    volumes:
      - ./src:/app/src
    restart: always